version: 2

sources:
  - name: dbakalov
    database: econ250-2025
    schema: dbakalov
    tables:
      - name: sheet_external
      - name: assignment1_full

  - name: google_trends
    database: bigquery-public-data
    schema: google_trends
    tables:
      - name: international_top_terms
